### ISSUE TITLE
folder structure 

### ISSUE THREAD

**Issue by luisfos** [jamesrobinsonvfx/mplay_batch#1]
like other 3rd party packages (aelib, mops, etc), it would be good to need only the contents of houdini18.5, so that we can keep its install separate from the $HOUDINI_USER_PREF_DIR. As that commonly needs to be cleared out when preferences corrupt.

**Comment by jamesrobinsonvfx** [comment]
hi @luisfos, thanks for your comment!

The `MPLAY_BATCH_INSTALL_DIR` key can be modified to point to any location on disk if you'd like to install to a custom location: https://github.com/jamesrobinsonvfx/mplay_batch/blob/783617009dbf0f40d76a1e65dd2e5c1b2bd47d60/mplay_batch.json#L5

(For instance, in my personal setup, I set it to a location completely separate from `$HOUDINI_USER_PREF_DIR` in my `$HSITE`)

The houdini18.5 directory is there so that the tool can be modified to be compatible with previous/future versions of Houdini. The correct version is loaded by Houdini when it compares the `houdini_version` keyword in the package. I will probably add and test a version for h18 soon in a couple of days (to make sure it's all backwards compatible), and when the next version of Houdini comes out, I'll create a houdini19.0 version for that one too. 

I will add a section to the README/gh-pages to do a better job of explaining this when I release the `ffmpeg_encode` branch. Please let me know if this clears things up at all. Thanks!

**Comment by jamesrobinsonvfx** [comment]
I added a more thorough demo [here](https://jamesrobinsonvfx.github.io/mplay_batch/#installing-to-an-hsite-demo). Going to close this issue unless there's anything else.

Thanks!
