### ISSUE TITLE
Python 3 support?

### ISSUE THREAD

**Issue by luisfos** [jamesrobinsonvfx/mplay_batch#13]
Hi James, thanks so much for this tool. It makes using Mplay so much better and I now can't work without it! 

Did an install on a machine using 18.5 Python 3, didn't seem to work. Guessing it's not setup for python 3.
Received the following when pressing any button in the batch menu:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'mplay_batch' has no attribute 'main'`

Cheers

**Comment by jamesrobinsonvfx** [comment]
hey @luisfos no problem!

You're right, it's not quite set up for Python 3 just yet. I was actually working on getting it ready over the weekend but got a bit sidetracked. I'll try and get to it this week and update this issue when it's ready.

**Comment by jamesrobinsonvfx** [comment]
This was actually quite a bit simpler to implement than I had originally planned. Initially it was a little tricky cause of the way py3 and py2 differ in importing modules. Since all the code is contained in a single module anyways, having a package was a little unnecessary so I just moved `mplay_batch.py` under  `python2.7libs` and made sure the code was all python3 friendly and it loads just fine so far! 

I will be releasing this tonight.
